import {SETS,APP_VERSION} from '../data/sets';
export function mount(){document.querySelector('#app')!.innerHTML=`
<header class="header"><span class="brand">ARおばけ探偵団</span><span class="version">実機検証 / 01</span></header>
<main class="shell">
<div class="heading"><div><p class="eyebrow">CAMERA & IMAGE TRACKING</p><h1>マーカー検証</h1><p>カードにカメラを向けて、おばけが現れるか確かめよう。</p></div><a class="text-link" href="./print.html" target="_blank" rel="noopener">マーカーを印刷 ↗</a></div>
<div class="workspace"><div class="main-column">
<section class="camera-panel" aria-label="ARカメラ"><div class="camera-top"><span id="camera-label"></span><span id="status" class="status-pill" role="status">停止中</span></div><div class="camera-stage" id="stage"><div class="scan-guide"></div><div class="camera-empty" id="overlay"><span class="crosshair">＋</span><h2 id="overlay-title">まずは、1枚から。</h2><p id="overlay-text"></p></div><div id="found-badge" class="found-badge" hidden></div></div><div class="camera-bottom" id="guidance" aria-live="polite">カード全体を映し、ゆっくり近づけてください。</div></section>
<section class="metrics" aria-label="動作の記録"><div><span>AR準備時間</span><strong id="startup">—</strong><small>許可後〜準備完了</small></div><div><span>連続動作</span><strong id="elapsed">00:00</strong><small>AR準備完了から</small></div><div><span>描画FPS</span><strong id="fps">—</strong><small>認識頻度とは別</small></div><div><span>認識回数</span><strong id="found-count">0</strong><small>再認識も含む</small></div></section>
<section class="surface trial-panel"><div class="section-line"><div><p class="eyebrow">RECOGNITION TEST</p><h2>読取時間を測る</h2></div><span class="small-tag">任意</span></div><p class="note">カードを画面の外に出し、計測開始と同時に見せてください。操作時間を含む目安です。10秒で未検出として記録します。</p><div class="trial-controls"><label class="sr-only" for="expected">計測するマーカー</label><select id="expected"></select><button class="secondary" id="trial-start" disabled>計測開始</button></div><p id="trial-result" class="trial-result" aria-live="polite">カメラを開始すると計測できます。</p><p id="trial-summary" class="note">まだ計測していません。</p></section></div>
<aside class="controls"><p class="eyebrow">TEST SETUP</p><h2>検証の準備</h2><label id="set-label">マーカーセット</label><div class="set-options" role="group" aria-labelledby="set-label">${Object.entries(SETS).map(([id,s])=>`<button type="button" class="set-option ${id==='one'?'selected':''}" data-set="${id}" aria-pressed="${id==='one'}">${s.ids.length}<span>枚</span></button>`).join('')}</div><p class="note" id="set-description"></p><label for="resolution">カメラ解像度の目安</label><select id="resolution"><option value="640">640 × 480（軽量）</option><option value="960">960 × 720</option></select><label for="device-note">端末メモ</label><input id="device-note" maxlength="100" placeholder="例：Air 2 / iPadOS 15.8" autocomplete="off"><p class="note small">実際の解像度は開始後に記録します。</p><button class="primary" id="start">カメラを開始</button><button class="secondary stop" id="stop" disabled>停止する</button><p class="note small">カメラ映像は送信・保存しません。</p><p id="notice" class="notice" role="status" hidden></p><div class="divider"></div><h3>確認すること</h3><ol class="steps"><li>1枚で表示と追従を確認</li><li>4枚、9枚へ切り替えて確認</li><li>10分間続け、記録を保存</li></ol><a class="text-link" href="./guide.html" target="_blank" rel="noopener">実機テストの手順 ↗</a></aside></div>
<section class="surface log-panel"><div class="section-line"><div><p class="eyebrow">SESSION LOG</p><h2>検証の記録</h2></div><button id="export" class="secondary">記録を保存</button></div><p class="note" id="session-note">この端末の直近10回分をJSONで保存できます。</p><div class="log-header"><span>時刻</span><span>できごと</span></div><ol id="events" class="events"></ol></section><footer>検証版 ${APP_VERSION} · MindAR 1.2.5 / Three.js 0.160.0 <span>Air 2の実機合格は、記録を確認して判断してください。</span></footer></main>`;}
export const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
